# -*- coding: utf-8 -*-
"""sasi.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eAkjsKI42lvD_k31SKEwd8DtcSctkkPv
"""

print('hello world')

print('hello\nworld')

print('sasi\nreddy')

print('sasi\tkumar\treddy\tchintala')

"""\n for new line charecter # new line charecter
\t for space # horizontal tab

#new line charecter
#horizontal tab
"""

print('\'hello\'')

print('\'sasi\'')

print('\\sasi\\')

print('sasi\n\tgitam\n\t\tindia')

print('*\n**\n***')

print('    *\n*\t*\n    *')

"""# variables"""

a= 10
print(a)

b=20.9
print(b)

a='in'

a = 'india'
print(a)

"""#data types
#type function
"""

a=10
print('a')
print(type(a))

a=20.8
print(a)
print(type(a))

a='sasi'
print(a)
print(type(a))

a=30
print(a+20)
print(a)

a=30
a=30+20
print(a)

"""#getting values from user"""

a=input()
print(a)

a=input('enter your pin\n')
print(a)

a=input('enter a number:')
print(a)

x=input('Enter your name\t')
print('Hello',x)

password=input('Enter your password:')
print('you password is :',password)

"""#type conversion"""

a=10
b='30'
print(type(a))
print(type(b))
c=int(b)
print(a+c)
print(type(c))

a=10
b=30
print(type(a))
print(type(b))
c=str(a)
d=str(b)
print(type(c))
print(type(d))
print(c+d)

"sasi"+"reddy"

a=10.9
print(a)
print(type(a))
b=int(a)
print(type(b))
print(b)

"""#first program in python"""

a=int(input('enter a number'))
b=int(input('enetr a number'))
print(a+b)

a=input('enter a number')
b=input('enetr a number')
c=int(a)
d=int(b)
print(c+d)

a=int(input('enter a number'))
b=int(input('enetr a number'))
print('addition of two numbers is :',a+b)

a=int(input('enter a number'))
b=int(input('enetr a number'))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

a=int(input('enter a number'))
b=int(input('ENTER A NUMBER'))
c=a+b
print('addition =',c)
c=a-b
print('substraction =',c)
c=a*b
print('multiplication =',c)
c=a/b
print('division =',c)

a=int(input('enter a number'))
b=int(input('enetr a number'))
c=a+b
print('addition =',c)
d=a-b
print('substraction =',d)
e=a*b
print('multiplication =',e)
f=a/b
print('division =',f)

a=str(input('enter yur name'))
b=str(input('enter your name'))
c=a+b
print('you name is',c)

x=int(input('ENTER THE LENGTH OF A SQUARE'))
area=x*x #x**2
print('THE AREA OF A SQUARE IS',area)

R=int(input('enter the radius of a '))
pi=22/7
area=pi*R*R
print('AREA OF A CIRCLE IS',area)

R=float(input('enter the radius of a '))
pi=3.14
area=pi*R*R
print('AREA OF A CIRCLE IS',area)

a=str(input('ENTER YOUR NAME '))
print('HELLO, HOW ARE YOU ?',a)

print('_\n  |_\n    |_\n      |')

"""#arthametic operators"""

+,-,*,/,//,**,%

10//2

10**2

"""#modulo %"""

10%2 # reminder

"""#floor division
#floor value removes the decimal part
#selling value gives round figure
"""

7//2

"""#exponents"""

2**3

7**2

"""#relational operators

<,>,>=,<=,==,=!
"""

a=int(input('ENETR A NUMBER'))
b=int(input('enter a number'))
print(a>b)

a=int(input('enter you atm pin'))
a==3149

10!=10

10!=2

"""#bitwise operators

& -> bitwise and
| -> bitwise or
^ -> bitwise xor
<< -> bitwise left shift
>> -> bitwise right shift

#binary numbers
"""

print(10&2)

"""0 & 0 -> 0
      0 & 1 -> 0
      1 & 0 -> 0
      1 & 1 -> 1

64 32 16 8 4 2 1
              1 0 1 0
              0 0 1 0
              0 0 1 0
"""

print(8&2)

"""64 32 16 8 4 2 1
               1 0 0 0
               0 0 1 0
               0 0 0 0

#bitwise or
"""

print(10|2)

"""64 32 16 8 4 2 1
              1 0 1 0
              0 0 1 0
              1 0 1 0

0 | 0 -> 0
        0 | 1 -> 1
        1 | 0 -> 1
        1 | 1 -> 1

#bitwise xor

0 ^ 0 -> 0
                  0 ^ 1 -> 1
                  1 ^ 0 -> 1
                  1 ^ 1 -> 0
"""

print(8^2)

"""64 32 16 8 4 2 1
               1 0 0 0
               0 0 1 0
               1 0 1 0

#<< left shift
"""

print(10<<2)

"""       1010
       0010
       00001010
       00010100
"""

print(24<<3)

"""11000
             00011000
             00110000
             01100000
             11000000

#>> right shift
"""

print(10>>3)

"""1010
                   00001010
                   00000101
                   10000010
                   01000001

#boolen and logical operators

#boolen operators

True

False

#logical operators
not


and


or
"""

print(not True)

print(not False)

"""#Truth table for and
False=0 true=1

False and False = False

False and True = False

True and False = False

True and True = True
"""

print(False and False)

print(False and True)

print(False and True and False and True)

"""#Truth table for or
False=0 true=1

False and False = False

False and True = True

True and False = True

True and True = True

"""

print(False or True)

print(True or False or True or False or False)

"""#combine all the logic operators

#priority
not

and

or
"""

print(False and not True or False and not False or True and not False and True)

"""False and False or False and True or True and True and True
    False or False or True
    False or True
    True

#Assignment and compound operators

# Assignment operator
=
"""

a=10
print(a)
a=30
print(a)

"""#Compound operators
  +=,  -=,  *=,  /=,  **=,  //=,  %=
"""

a=10
a+=5 #a=a+5
print(a)

a=10
a-=2
print(a)

a=10
a*=5
print(a)

a=10
a/=5
print(a)

a=3
a**=3
print(a)

a=7
a//=2
print(a)

a=7
a%=2
print(a)

"""#Conditional statements if and else"""

a=10
if (a>5):
    print('hello')

a=10
b=9
if(a<b):
  print('hi')

pin=3149
get_pin=int(input('Enter your pin:'))
if get_pin==pin:
  print('collect your cash')
else:
    print('your pin is incorrect')

n=int(input('Enter a number'))
if n>=0:
  print('absolute value :',n)
else:
  print('absolute value :',n*(-1))

"""#nested if andelse"""

a=int(input('Enetr a number'))
if a>5:
  print(1)
  if a>8:
    print(2)
  else:
      print(3)
      if a==9:
        print(4)
      elif a==10:
          print(5)
      else:
        print(6)
else:
  print(7)
  if a==1:
    print(8)

"""# Example 1 : Number checker num = 5 if num > 0: print("The number is positive.") else: if num < 0: print("The number is negative.") else: print("The number is zero.")"""

n=5
if n>0:
  print('The number is positive',n)
else:
  if n<0:
    print('The number is negative',n)
  else:
    if n==0:
      print('The number is zero',n)

n=-5
if n>0:
  print('The number is positive',n)
else:
  if n<0:
    print('The number is negative',n)
  else:
    if n==0:
      print('The number is zero',n)

n=0
if n>0:
  print('The number is positive',n)
else:
  if n<0:
    print('The number is negative',n)
  else:
    if n==0:
      print('The number is zero',n)

""" # Example 2 : Age classifier age = 35 if age >= 60: print("You are a senior citizen.") else: if age >= 18: print("You are an adult.") else: print("You ..."""

age=int(input('enter a number'))
if age>=60:
  print('You are a senior citizen',age)
else:
  if age>=18:
    print('You are an adult',age)
  if age<18:
    print('You are an minor',age)

age=int(input('enter a number'))
if age>=60:
  print('You are a senior citizen',age)
else:
  if age>=18:
    print('You are an adult',age)
  if age<18:
    print('You are an minor',age)

age=int(input('enter a number'))
if age>=60:
  print('You are a senior citizen',age)
else:
  if age>=18:
    print('You are an adult',age)
  if age<18:
    print('You are an minor',age)

"""#write a program to enter a number from user and check if it is grater than 10 or not"""

n=int(input('enter a number'))
if n>10:
  print('Yes',n)
else:
  print('No',n)

n=int(input('enter a number'))
if n>10:
  print('Yes',n)
else:
  print('No',n)

n=int(input('enter a number'))
if n>10:
  print('Grater')
else:
  print('Small')

n=int(input('enter a number'))
if n>10:
  print('Grater')
elif n==10:
  print('Equal')
else:
  print('Small')

"""#write a program to enter 3 numbers from the user and check and print the Grater number"""

a=int(input('Enter the 1 st number :'))
b=int(input('Enter the 2 nd number :'))
c=int(input('Enetr the 3 rd number :'))
if a>=b:
  print('Grater =',b)
  if a>=c:
    print('Grater =',c)
else:
  print('Grater =',b)

a=int(input('Enter the 1 st number :'))
b=int(input('Enter the 2 nd number :'))
c=int(input('Enetr the 3 rd number :'))
if a>=b:
  print('Grater =',b)
  if a>=c:
    print('Grater =',c)
else:
  if b>=c:
    print('Grater =',b)
  else:
    print('Grater =',c)

"""# write a program to enter a number between 0 to 9 and print its character format"""

n=int(input('Enetr a number'))
if n==0:
  print('Zero')
elif n==1:
  print('One')
elif n==2:
  print('Two')
elif n==3:
  print('Three')
elif n==4:
  print('Four')
elif n==5:
  print('Five')
elif n==6:
  print('Six')
elif n==7:
  print('Seven')
elif n==8:
  print('Eight')
elif n==9:
  print('Nine')
else:
  print('invalid value')



"""#write a program to enter a character from the user and check if it is vowell or consonent"""

ch = str(input('Enter a charecter'))
if ch=='a':
  print('Vowel')
elif ch=='e':
  print('Vowel')
elif ch=='i':
  print('Vowel')
elif ch=='o':
  print('Vowel')
elif ch=='u':
  print('Vowel')
else:
  print('Consonent :',ch)

ch = str(input('Enter a charecter'))
if ch=='a'or ch=='e'or ch=='i'or ch=='o'or ch=='u':
  print('Vowel')

else:
  print('Consonent :',ch)

"""# while loop"""

i=1
while i<=5:
  print('India')
  i+=1

1
2
3
4
5

i=1
while i<=5:
  print(i)
  i+=1

i=1
while i<6:
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

i=1
while i<=20:
  print(i)
  i+=1

"""#number series questions using
#     while loop
"""

print('Hello')
print('User')

print('Hello',end='\n')
print('User')

print('Hello',end=' ')
print('User')

print('Hello',end='\t')
print('User')

print('Hello',end='+')
print('User')

print('Hello',end='')
print('User')

1  2  3  4  5  6  7  8  9  10

i=1
while i<=10:
  print(i,end='  ')
  i+=1

i=1
while i<=10:
  print(i,end='\t')
  i+=1

1  4  9  16  25  36  49  81  100

i=1
while i<=10:
  print(i*i,end='  ')
  i+=1

a=10
print(a+10,a)

a=10
a=a+10
print(a+10)
print(a)

"""#break statment

the 'break' statement will break the loop
"""

i=1
while i<=10:
  print(i)
  break
print('Finish')

i=1
while i<=10:
  if i==5:
    print(i)
    break
  else:
    print(i)
  i+=1
print('Finish')

"""#continue statement
the 'continue' statement will rotate the loop
"""

i=0
while i<=10:
  i+=1
  if i%2==0:
    continue
  else:
    print(i)
print('INDORE')

"""#write a program to print 10 even numbers"""

i=0
while i<=20:
  i+=2
  print(i,end='  ')

i=0
while i<=20:
  print(i,end='  ')
  i+=2

i=2
while i<=20:
  print(i,end='  ')
  i+=2

i=1
while i<=20:
  if i%2==0:
    print(i,end='  ')
  i+=1

"""# write a program to print 10 odd numbers"""

i=1
while i<=20:
  print(i,end='  ')
  i+=2

i=1
while i<=20:
  if i%2==1:
    print(i,end='  ')
  i+=1

i=1
while i<=10:
  print(i,'/',i*i,end='  ')
  i+=1

i=1
while i<=10:
  print(i,end='/')
  print(i*i,end='  ')
  i+=1

i=1
while i<=10:
  print(i,end='+')
  i+=1

i=1
while i<=10:
  if i<10:
    print(i,end='+')
  else:
    print(i)
  i+=1

"""#nested while loop"""

11  12  13
21  22  23
31  32  33

i=1
j=1
while i<=3:
  while j<=3:
    print(i,j,end='  ')
    j+=1
  print()
  i+=1

print('Hi')
print()
print('Bye')

"""print() changes the line instead of print() we can use print(end='\n')"""

i=1
#j=1
while i<=3:
    j=1
    while j<=3:
      print(i,j,end='  ')
      j+=1
    print()
    i+=1

i=1
while i<=3:
  j=1
  while j<=3:
    print(i,end='')
    print(j,end='  ')
    j+=1
  print()
  i+=1

"""the internal loop is used to print the value and the external loop is used to change the value"""

i=1
while i<=5:
  j=1
  while j<=i:
    print('*',end='')
    j+=1
  print()
  i+=1

1
12
123
1234
12345

i=1
while i<=5:
  j=1
  while j<=i:
    print(j,end='')
    j+=1
  print()
  i+=1